local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

private.DB = private.DB or {}
private.DB.DragonflightEventsDB = {
        [180] = {
            id=180,
            label=Locale["615_dragon_isles_reawaken"],
            chapters={{
                header = Locale[""],
                pages = {Locale["616_ancient_wards_fail_and_the_dragon_isles_awaken__ca"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=2,
            timeline=1,
            order=0,
            characters={["dragonflight"] = {79, 81, 82}},
            factions={["dragonflight"] = {57, 58, 59}},
        },
        [181] = {
            id=181,
            label=Locale["617_raszageth_freed"],
            chapters={{
                header = Locale[""],
                pages = {Locale["618_raszageth_is_released_and_rallies_primalist_forces"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=3,
            timeline=1,
            order=1,
            characters={["dragonflight"] = {79, 80, 81}},
            factions={["dragonflight"] = {58, 57, 59}},
        },
        [182] = {
            id=182,
            label=Locale["619_vault_of_the_incarnates"],
            chapters={{
                header = Locale[""],
                pages = {Locale["620_champions_storm_the_vault_of_the_incarnates_and_en"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=2,
            characters={["dragonflight"] = {80, 79, 81}},
            factions={["dragonflight"] = {58, 57}},
        },
        [183] = {
            id=183,
            label=Locale["621_aberrus_and_fyrakk's_ascendance"],
            chapters={{
                header = Locale[""],
                pages = {Locale["622_ancient_draconic_secrets_in_aberrus_are_claimed_am"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=3,
            characters={["dragonflight"] = {81, 82, 83}},
            factions={["dragonflight"] = {58, 57, 60}},
        },
        [184] = {
            id=184,
            label=Locale["623_amirdrassil_restored___fall_of_fyrakk"],
            chapters={{
                header = Locale[""],
                pages = {Locale["624_the_defense_of_amirdrassil_culminates_in_fyrakk's_"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=4,
            characters={["dragonflight"] = {83, 79, 82}},
            factions={["dragonflight"] = {60, 57, 58}},
        },
        [310] = {
            id=310,
            label=Locale["933_exploring_azeroth__northrend"],
            chapters={{
                header = Locale[""],
                pages = {Locale["934_exploring_azeroth__northrend"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [311] = {
            id=311,
            label=Locale["935_exploring_azeroth__pandaria"],
            chapters={{
                header = Locale[""],
                pages = {Locale["936_exploring_azeroth__pandaria"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=6,
            characters={},
            factions={},
        },
        [312] = {
            id=312,
            label=Locale["937_the_vow_eternal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["938_the_vow_eternal"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=7,
            characters={},
            factions={},
        },
        [313] = {
            id=313,
            label=Locale["939_a_tempest_is_unleashed_across_azeroth__and_is_cont"],
            chapters={{
                header = Locale[""],
                pages = {Locale["940_a_tempest_is_unleashed_across_azeroth__and_is_cont"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [314] = {
            id=314,
            label=Locale["941_the_dracthyr_awaken_from_stasis_in_the_forbidden_r"],
            chapters={{
                header = Locale[""],
                pages = {Locale["942_the_dracthyr_awaken_from_stasis_in_the_forbidden_r"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [315] = {
            id=315,
            label=Locale["943_alliance_and_horde_expeditions_travel_to_the_drago"],
            chapters={{
                header = Locale[""],
                pages = {Locale["944_alliance_and_horde_expeditions_travel_to_the_drago"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [316] = {
            id=316,
            label=Locale["945_adventurers_manage_to_kill_raszageth_in_the_vault_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["946_adventurers_manage_to_kill_raszageth_in_the_vault_"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=11,
            characters={["dragonflight"] = {80}},
            factions={["dragonflight"] = {58}},
        },
        [317] = {
            id=317,
            label=Locale["947_after_hardships__the_windtotem_tribe_of_tauren_set"],
            chapters={{
                header = Locale[""],
                pages = {Locale["948_after_hardships__the_windtotem_tribe_of_tauren_set"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=1,
            timeline=1,
            order=12,
            characters={},
            factions={},
        },
        [318] = {
            id=318,
            label=Locale["949_lord_banehollow__disguised_as_madam_shadow_tries_t"],
            chapters={{
                header = Locale[""],
                pages = {Locale["950_lord_banehollow__disguised_as_madam_shadow_tries_t"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=3,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [319] = {
            id=319,
            label=Locale["951_the_orc_nation_of_durotar_celebrates_their_first_a"],
            chapters={{
                header = Locale[""],
                pages = {Locale["952_the_orc_nation_of_durotar_celebrates_their_first_a"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [320] = {
            id=320,
            label=Locale["953_mortals_enter_zaralek_cavern_and_team_up_with_the_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["954_mortals_enter_zaralek_cavern_and_team_up_with_the_"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=15,
            characters={},
            factions={["worldofwarcraft"] = {25}},
        },
        [321] = {
            id=321,
            label=Locale["955_fyrakk_is_empowered_with_shadowlame_and_runs_rampa"],
            chapters={{
                header = Locale[""],
                pages = {Locale["956_fyrakk_is_empowered_with_shadowlame_and_runs_rampa"]} }},
            yearStart=40,
            yearEnd=40,
            eventType=4,
            timeline=1,
            order=16,
            characters={["dragonflight"] = {81, 83}},
            factions={},
        }
    }