local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

private.DB = private.DB or {}
private.DB.LichkingEventsDB = {
        [145] = {
            id=145,
            label=Locale["423_northrend_campaign_begins"],
            chapters={{
                header = Locale[""],
                pages = {Locale["424_alliance_and_horde_launch_their_northern_war_again"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=2,
            timeline=1,
            order=0,
            characters={["greatwars"] = {31}, ["lichking"] = {43, 45}},
            factions={["greatwars"] = {13, 15, 1}, ["lichking"] = {32}},
        },
        [146] = {
            id=146,
            label=Locale["425_battle_of_the_wrathgate_and_the_undercity_crisis"],
            chapters={{
                header = Locale[""],
                pages = {Locale["426_the_wrathgate_disaster_shocks_both_factions__and_t"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=1,
            timeline=1,
            order=1,
            characters={["greatwars"] = {21}, ["lichking"] = {43}},
            factions={["greatwars"] = {13, 15, 1}},
        },
        [147] = {
            id=147,
            label=Locale["427_ulduar_and_the_fall_of_yogg_saron"],
            chapters={{
                header = Locale[""],
                pages = {Locale["428_in_ancient_ulduar__brann_and_azeroth's_champions_u"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=4,
            timeline=1,
            order=2,
            characters={["lichking"] = {46, 47}},
            factions={["greatwars"] = {15, 1, 13}, ["lichking"] = {34}},
        },
        [148] = {
            id=148,
            label=Locale["429_argent_tournament_and_the_ebon_blade_offensive"],
            chapters={{
                header = Locale[""],
                pages = {Locale["430_the_argent_tournament_forges_a_united_assault_forc"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=3,
            characters={["lichking"] = {45, 44}},
            factions={["greatwars"] = {15, 1, 13}, ["lichking"] = {32, 33}},
        },
        [149] = {
            id=149,
            label=Locale["431_assault_on_icecrown_citadel___fall_of_the_lich_kin"],
            chapters={{
                header = Locale[""],
                pages = {Locale["432_the_final_assault_breaches_icecrown_citadel__the_l"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=4,
            timeline=1,
            order=4,
            characters={["greatwars"] = {31}, ["lichking"] = {44, 45, 43}},
            factions={["greatwars"] = {15, 1, 13}, ["lichking"] = {32, 33}},
        },
        [227] = {
            id=227,
            label=Locale["767_the_blue_dragon_aspect_malygos_begins_redirecting_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["768_the_blue_dragon_aspect_malygos_begins_redirecting_"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=4,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [228] = {
            id=228,
            label=Locale["769_the_second_scourge_invasion___the_lich_king_begins"],
            chapters={{
                header = Locale[""],
                pages = {Locale["770_patch_3_0_2_echoes_of_doom__the_second_scourge_inv"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=6,
            characters={["greatwars"] = {31}},
            factions={["greatwars"] = {13}},
        },
        [229] = {
            id=229,
            label=Locale["771_wrath_of_the_lich_king_campaign__the_war_against_t"],
            chapters={{
                header = Locale[""],
                pages = {Locale["772_patch_3_0_3_wrath_of_the_lich_king__the_alliance_a"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=7,
            characters={["greatwars"] = {31}},
            factions={},
        },
        [230] = {
            id=230,
            label=Locale["773_naxxramas__raid"],
            chapters={{
                header = Locale[""],
                pages = {Locale["774_patch_3_0_3_wrath_of_the_lich_king__the_alliance_a"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=1,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [231] = {
            id=231,
            label=Locale["775_nexus_war"],
            chapters={{
                header = Locale[""],
                pages = {Locale["776_patch_3_0_3_wrath_of_the_lich_king__nexus_war___th"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [232] = {
            id=232,
            label=Locale["777_the_obsidian_sanctum__raid"],
            chapters={{
                header = Locale[""],
                pages = {Locale["778_patch_3_0_3_wrath_of_the_lich_king__as_a_nesting_g"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [233] = {
            id=233,
            label=Locale["779_battle_of_angrathar_the_wrathgate"],
            chapters={{
                header = Locale[""],
                pages = {Locale["780_patch_3_0_3_wrath_of_the_lich_king__battle_of_angr"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=11,
            characters={},
            factions={},
        },
        [234] = {
            id=234,
            label=Locale["781_li_li_stormstout__after_having_explored_the_limits"],
            chapters={{
                header = Locale[""],
                pages = {Locale["782_patch_3_0_3_wrath_of_the_lich_king__li_li_stormsto"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=4,
            timeline=1,
            order=12,
            characters={},
            factions={},
        },
        [235] = {
            id=235,
            label=Locale["783_the_second_of_the_vault_of_archavon's_four_watcher"],
            chapters={{
                header = Locale[""],
                pages = {Locale["784_patch_3_1_0_secrets_of_ulduar__the_second_of_the_v"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=4,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [236] = {
            id=236,
            label=Locale["785_the_horde_and_alliance_leaders_gather_in_the_viole"],
            chapters={{
                header = Locale[""],
                pages = {Locale["786_patch_3_1_0_secrets_of_ulduar__the_horde_and_allia"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=1,
            timeline=1,
            order=14,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [237] = {
            id=237,
            label=Locale["787_garrosh_hellscream__heart_of_war__short_story"],
            chapters={{
                header = Locale[""],
                pages = {Locale["788_patch_3_1_0_secrets_of_ulduar__garrosh_hellscream_"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=3,
            timeline=1,
            order=15,
            characters={["cataclysm"] = {49}},
            factions={},
        },
        [238] = {
            id=238,
            label=Locale["789_ulduar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["790_patch_3_1_0_secrets_of_ulduar__the_alliance_and_ho"]} }},
            yearStart=27,
            yearEnd=27,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }