local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    GreatwarsEventsDB = {
        [102] = {
            id=102,
            label=Locale["211_arrival_of_the_horde_through_the_dark_portal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["212_the_orcish_horde_emerges_on_azeroth_through_the_da"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=0,
            characters={["greatwars"] = {9}},
            factions={["greatwars"] = {1, 2}},
        },
        [103] = {
            id=103,
            label=Locale["213_khadgar_becomes_medivh's_apprentice"],
            chapters={{
                header = Locale[""],
                pages = {Locale["214_the_young_mage_khadgar_is_sent_to_study_under_medi"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=1,
            characters={["greatwars"] = {2, 3, 4}},
            factions={},
        },
        [104] = {
            id=104,
            label=Locale["215_banishment_of_the_frostwolves"],
            chapters={{
                header = Locale[""],
                pages = {Locale["216_durotan_and_the_frostwolf_clan_are_cast_out_from_t"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=2,
            characters={["greatwars"] = {5}},
            factions={["greatwars"] = {1, 3}},
        },
        [105] = {
            id=105,
            label=Locale["217_birth_of_thrall___death_of_durotan_and_draka"],
            chapters={{
                header = Locale[""],
                pages = {Locale["218_thrall_is_born_to_durotan_and_draka_shortly_before"]} }},
            yearStart=1,
            yearEnd=1,
            eventType=1,
            timeline=1,
            order=15,
            characters={["greatwars"] = {7, 5, 6, 8}, ["warlords"] = {61}},
            factions={["greatwars"] = {3}},
        },
        [106] = {
            id=106,
            label=Locale["219_death_of_medivh___orgrim_kills_blackhand"],
            chapters={{
                header = Locale[""],
                pages = {Locale["220_khadgar__garona__and_their_allies_bring_down_mediv"]} }},
            yearStart=3,
            yearEnd=3,
            eventType=1,
            timeline=1,
            order=16,
            characters={["greatwars"] = {2, 4, 3, 8, 9}},
            factions={["greatwars"] = {1, 4}},
        },
        [107] = {
            id=107,
            label=Locale["221_fall_of_stormwind___assassination_of_king_llane"],
            chapters={{
                header = Locale[""],
                pages = {Locale["222_stormwind_falls_to_the_horde_after_garona_assassin"]} }},
            yearStart=3,
            yearEnd=3,
            eventType=4,
            timeline=1,
            order=17,
            characters={["greatwars"] = {4, 10}},
            factions={["greatwars"] = {1, 2}},
        },
        [108] = {
            id=108,
            label=Locale["249_formation_of_the_council_of_seven_nations"],
            chapters={{
                header = Locale[""],
                pages = {Locale["250_following_the_fall_of_stormwind__the_human_kingdom"]} }},
            yearStart=4,
            yearEnd=4,
            eventType=1,
            timeline=1,
            order=18,
            characters={["greatwars"] = {11, 16}},
            factions={["greatwars"] = {6}},
        },
        [109] = {
            id=109,
            label=Locale["251_formation_of_the_alliance_of_lordaeron"],
            chapters={{
                header = Locale[""],
                pages = {Locale["252_the_kingdoms_of_humanity_and_their_allies_formally"]} }},
            yearStart=5,
            yearEnd=5,
            eventType=2,
            timeline=1,
            order=19,
            characters={["greatwars"] = {11, 16}},
            factions={["greatwars"] = {5, 6, 15}},
        },
        [110] = {
            id=110,
            label=Locale["253_founding_of_the_order_of_the_silver_hand"],
            chapters={{
                header = Locale[""],
                pages = {Locale["254_uther_lightbringer_and_the_clergy_of_lordaeron_fou"]} }},
            yearStart=5,
            yearEnd=5,
            eventType=1,
            timeline=1,
            order=20,
            characters={["greatwars"] = {12}},
            factions={["greatwars"] = {7, 5}},
        },
        [111] = {
            id=111,
            label=Locale["255_alexstrasza_captured_at_grim_batol"],
            chapters={{
                header = Locale[""],
                pages = {Locale["256_the_dragonmaw_clan_enslaves_alexstrasza_at_grim_ba"]} }},
            yearStart=5,
            yearEnd=5,
            eventType=1,
            timeline=1,
            order=21,
            characters={["greatwars"] = {14, 15}, ["dragonflight"] = {79}},
            factions={["greatwars"] = {8, 1}},
        },
        [112] = {
            id=112,
            label=Locale["257_gul'dan_creates_the_first_death_knights"],
            chapters={{
                header = Locale[""],
                pages = {Locale["258_gul'dan_pioneers_necromantic_warfare_by_creating_t"]} }},
            yearStart=5,
            yearEnd=5,
            eventType=1,
            timeline=1,
            order=22,
            characters={["greatwars"] = {13}},
            factions={["greatwars"] = {4, 9}},
        },
        [113] = {
            id=113,
            label=Locale["259_battle_of_hillsbrad"],
            chapters={{
                header = Locale[""],
                pages = {Locale["260_horde_and_alliance_forces_clash_in_hillsbrad_as_th"]} }},
            yearStart=6,
            yearEnd=6,
            eventType=4,
            timeline=1,
            order=23,
            characters={["greatwars"] = {17}},
            factions={["greatwars"] = {10, 5, 1}},
        },
        [114] = {
            id=114,
            label=Locale["261_siege_of_lordaeron___gul'dan's_betrayal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["262_the_horde_presses_its_assault_into_the_heart_of_lo"]} }},
            yearStart=6,
            yearEnd=6,
            eventType=4,
            timeline=1,
            order=24,
            characters={["greatwars"] = {13, 8, 16}},
            factions={["greatwars"] = {5, 1, 4}},
        },
        [115] = {
            id=115,
            label=Locale["263_death_of_anduin_lothar_at_blackrock_spire"],
            chapters={{
                header = Locale[""],
                pages = {Locale["264_anduin_lothar_falls_in_battle_against_orgrim_doomh"]} }},
            yearStart=6,
            yearEnd=6,
            eventType=5,
            timeline=1,
            order=25,
            characters={["greatwars"] = {11, 8}},
            factions={["greatwars"] = {5, 1}},
        },
        [116] = {
            id=116,
            label=Locale["265_khadgar_destroys_the_dark_portal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["266_khadgar_destroys_the_dark_portal_at_the_end_of_the"]} }},
            yearStart=6,
            yearEnd=6,
            eventType=1,
            timeline=1,
            order=26,
            characters={["greatwars"] = {2}},
            factions={["greatwars"] = {5, 1}},
        },
        [117] = {
            id=117,
            label=Locale["267_ner'zhul_reopens_the_portal___draenor_shatters"],
            chapters={{
                header = Locale[""],
                pages = {Locale["268_ner'zhul_tears_open_multiple_portals_in_a_desperat"]} }},
            yearStart=7,
            yearEnd=7,
            eventType=1,
            timeline=1,
            order=27,
            characters={["greatwars"] = {18}},
            factions={["greatwars"] = {11, 1}},
        },
        [118] = {
            id=118,
            label=Locale["269_ner'zhul_becomes_the_lich_king"],
            chapters={{
                header = Locale[""],
                pages = {Locale["270_kil'jaeden_captures_ner'zhul_and_binds_his_spirit_"]} }},
            yearStart=7,
            yearEnd=7,
            eventType=1,
            timeline=1,
            order=28,
            characters={["greatwars"] = {18, 31}},
            factions={["greatwars"] = {12}},
        },
        [119] = {
            id=119,
            label=Locale["303_the_scourge_spreads_through_lordaeron"],
            chapters={{
                header = Locale[""],
                pages = {Locale["304_undeath_begins_to_spread_openly_across_lordaeron_a"]} }},
            yearStart=20,
            yearEnd=20,
            eventType=2,
            timeline=1,
            order=31,
            characters={["greatwars"] = {22}},
            factions={["greatwars"] = {13, 5}},
        },
        [120] = {
            id=120,
            label=Locale["305_culling_of_stratholme"],
            chapters={{
                header = Locale[""],
                pages = {Locale["306_arthas_orders_the_purge_of_stratholme_to_stop_its_"]} }},
            yearStart=20,
            yearEnd=20,
            eventType=1,
            timeline=1,
            order=32,
            characters={["greatwars"] = {19, 20, 23}},
            factions={["greatwars"] = {13, 5}},
        },
        [121] = {
            id=121,
            label=Locale["307_arthas_claims_frostmourne"],
            chapters={{
                header = Locale[""],
                pages = {Locale["308_in_northrend__arthas_takes_up_frostmourne_despite_"]} }},
            yearStart=20,
            yearEnd=20,
            eventType=1,
            timeline=1,
            order=33,
            characters={["greatwars"] = {19, 23}},
            factions={["greatwars"] = {13}},
        },
        [122] = {
            id=122,
            label=Locale["309_arthas_murders_king_terenas"],
            chapters={{
                header = Locale[""],
                pages = {Locale["310_upon_returning_to_lordaeron_as_a_death_knight__art"]} }},
            yearStart=20,
            yearEnd=20,
            eventType=5,
            timeline=1,
            order=34,
            characters={["greatwars"] = {19, 16}},
            factions={["greatwars"] = {13, 5}},
        },
        [123] = {
            id=123,
            label=Locale["311_invasion_of_quel'thalas_and_the_sunwell's_corrupti"],
            chapters={{
                header = Locale[""],
                pages = {Locale["312_arthas_invades_quel'thalas__slays_sylvanas__and_us"]} }},
            yearStart=21,
            yearEnd=21,
            eventType=3,
            timeline=1,
            order=35,
            characters={["greatwars"] = {19, 21, 22}},
            factions={["greatwars"] = {13, 14}},
        },
        [124] = {
            id=124,
            label=Locale["313_battle_of_mount_hyjal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["314_alliance__horde__and_night_elves_unite_at_hyjal_to"]} }},
            yearStart=21,
            yearEnd=21,
            eventType=4,
            timeline=1,
            order=36,
            characters={["greatwars"] = {7, 20, 24, 27}},
            factions={["greatwars"] = {15, 1, 16, 13}},
        },
        [125] = {
            id=125,
            label=Locale["315_illidan_attempts_to_destroy_the_frozen_throne"],
            chapters={{
                header = Locale[""],
                pages = {Locale["316_empowered_by_the_legion__illidan_tries_to_shatter_"]} }},
            yearStart=21,
            yearEnd=21,
            eventType=1,
            timeline=1,
            order=37,
            characters={["greatwars"] = {24}},
            factions={["greatwars"] = {17, 13}},
        },
        [126] = {
            id=126,
            label=Locale["317_kael'thas_and_the_blood_elves_join_illidan"],
            chapters={{
                header = Locale[""],
                pages = {Locale["318_kael'thas_leads_the_blood_elves_into_illidan's_ser"]} }},
            yearStart=21,
            yearEnd=21,
            eventType=1,
            timeline=1,
            order=38,
            characters={["greatwars"] = {25, 24}},
            factions={["greatwars"] = {17, 18}},
        },
        [127] = {
            id=127,
            label=Locale["319_founding_of_durotar_and_orgrimmar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["320_thrall_leads_the_horde_to_kalimdor_and_establishes"]} }},
            yearStart=23,
            yearEnd=23,
            eventType=1,
            timeline=1,
            order=39,
            characters={["greatwars"] = {7, 26, 20}},
            factions={["greatwars"] = {1}},
        },
        [128] = {
            id=128,
            label=Locale["321_the_forsaken_join_the_horde"],
            chapters={{
                header = Locale[""],
                pages = {Locale["322_sylvanas_secures_the_forsaken_a_place_within_the_h"]} }},
            yearStart=23,
            yearEnd=23,
            eventType=1,
            timeline=1,
            order=40,
            characters={["greatwars"] = {21, 7}},
            factions={["greatwars"] = {19, 1}},
        },
        [129] = {
            id=129,
            label=Locale["355_battle_of_grim_batol___liberation_of_alexstrasza"],
            chapters={{
                header = Locale[""],
                pages = {Locale["356_rhonin__vereesa__korialstrasz__and_their_allies_br"]} }},
            yearStart=10,
            yearEnd=10,
            eventType=4,
            timeline=1,
            order=29,
            characters={["greatwars"] = {14, 28, 29, 30}, ["dragonflight"] = {79}},
            factions={["greatwars"] = {8, 20}},
        },
        [130] = {
            id=130,
            label=Locale["357_war_of_the_spider"],
            chapters={{
                header = Locale[""],
                pages = {Locale["358_the_lich_king_wages_war_beneath_northrend_against_"]} }},
            yearStart=10,
            yearEnd=10,
            eventType=3,
            timeline=1,
            order=30,
            characters={["greatwars"] = {31}},
            factions={["greatwars"] = {13, 21}},
        },
        [191] = {
            id=191,
            label=Locale["695_the_horde_enter_the_dark_portal_and_small_skirmish"],
            chapters={{
                header = Locale[""],
                pages = {Locale["696_the_horde_enter_the_dark_portal_and_small_skirmish"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=3,
            characters={},
            factions={["greatwars"] = {1}},
        },
        [192] = {
            id=192,
            label=Locale["697_warcraft__orcs___humans_begins"],
            chapters={{
                header = Locale[""],
                pages = {Locale["698_warcraft__orcs___humans_begins"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=3,
            timeline=1,
            order=4,
            characters={},
            factions={},
        },
        [193] = {
            id=193,
            label=Locale["699_khadgar_is_taken_in_as_the_apprentice_of_the_guard"],
            chapters={{
                header = Locale[""],
                pages = {Locale["700_khadgar_is_taken_in_as_the_apprentice_of_the_guard"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=5,
            characters={["greatwars"] = {2, 3}},
            factions={},
        },
        [194] = {
            id=194,
            label=Locale["701_the_frostwolves_are_banished_from_the_horde_and_be"],
            chapters={{
                header = Locale[""],
                pages = {Locale["702_the_frostwolves_are_banished_from_the_horde_and_be"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=6,
            characters={},
            factions={["greatwars"] = {1}},
        },
        [195] = {
            id=195,
            label=Locale["703_blackhand_orders_the_horde_push_north_and_west__fa"],
            chapters={{
                header = Locale[""],
                pages = {Locale["704_blackhand_orders_the_horde_push_north_and_west__fa"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=7,
            characters={["greatwars"] = {9}},
            factions={["greatwars"] = {1}},
        },
        [196] = {
            id=196,
            label=Locale["705_the_bleeding_hollow_clan_pushes_into_stranglethorn"],
            chapters={{
                header = Locale[""],
                pages = {Locale["706_the_bleeding_hollow_clan_pushes_into_stranglethorn"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [197] = {
            id=197,
            label=Locale["707_to_combat_the_horde__the_northshire_clerics_begin_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["708_to_combat_the_horde__the_northshire_clerics_begin_"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={["greatwars"] = {1}},
        },
        [198] = {
            id=198,
            label=Locale["709_the_old_gods_begin_contacting_cho'gall_and_the_twi"],
            chapters={{
                header = Locale[""],
                pages = {Locale["710_the_old_gods_begin_contacting_cho'gall_and_the_twi"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=10,
            characters={["cataclysm"] = {50}},
            factions={["worldofwarcraft"] = {22}, ["cataclysm"] = {35}},
        },
        [199] = {
            id=199,
            label=Locale["711_the_frostwolves_arrive_in_alterac_valley__having_a"],
            chapters={{
                header = Locale[""],
                pages = {Locale["712_the_frostwolves_arrive_in_alterac_valley__having_a"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=11,
            characters={},
            factions={},
        },
        [200] = {
            id=200,
            label=Locale["713_redridge_falls_to_the_horde"],
            chapters={{
                header = Locale[""],
                pages = {Locale["714_redridge_falls_to_the_horde"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=4,
            timeline=1,
            order=12,
            characters={},
            factions={["greatwars"] = {1}},
        },
        [201] = {
            id=201,
            label=Locale["715_the_shadow_council_moves_their_operations_to_black"],
            chapters={{
                header = Locale[""],
                pages = {Locale["716_the_shadow_council_moves_their_operations_to_black"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=1,
            timeline=1,
            order=13,
            characters={},
            factions={["greatwars"] = {4}},
        },
        [202] = {
            id=202,
            label=Locale["717_the_horde_begins_their_first_siege_of_stormwind_ci"],
            chapters={{
                header = Locale[""],
                pages = {Locale["718_the_horde_begins_their_first_siege_of_stormwind_ci"]} }},
            yearStart=0,
            yearEnd=0,
            eventType=3,
            timeline=1,
            order=14,
            characters={},
            factions={["greatwars"] = {1, 2}},
        }
    }