name: Create Archive
on: [merge]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'C.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'