local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

private.DB = private.DB or {}
private.DB.ShadowlandsEventsDB = {
        [175] = {
            id=175,
            label=Locale["605_helm_of_domination_shattered"],
            chapters={{
                header = Locale[""],
                pages = {Locale["606_sylvanas_shatters_the_helm_of_domination_above_ice"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=2,
            timeline=1,
            order=0,
            characters={["legion"] = {66}, ["shadowlands"] = {76, 74}},
            factions={["greatwars"] = {1, 15}, ["shadowlands"] = {54}},
        },
        [176] = {
            id=176,
            label=Locale["607_maw_campaign_and_anduin's_captivity"],
            chapters={{
                header = Locale[""],
                pages = {Locale["608_azeroth's_champions_enter_the_maw__where_the_jaile"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=3,
            timeline=1,
            order=1,
            characters={["legion"] = {65}, ["shadowlands"] = {74, 76}},
            factions={["shadowlands"] = {53, 54, 55}},
        },
        [177] = {
            id=177,
            label=Locale["609_sanctum_of_domination"],
            chapters={{
                header = Locale[""],
                pages = {Locale["610_the_assault_on_the_sanctum_breaks_the_jailer's_hol"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=4,
            timeline=1,
            order=2,
            characters={["legion"] = {66, 65}, ["shadowlands"] = {76}},
            factions={["shadowlands"] = {54, 53, 56}},
        },
        [178] = {
            id=178,
            label=Locale["611_zereth_mortis_expedition"],
            chapters={{
                header = Locale[""],
                pages = {Locale["612_allied_forces_pursue_the_jailer_into_zereth_mortis"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=3,
            timeline=1,
            order=3,
            characters={["shadowlands"] = {74, 77, 78}},
            factions={["shadowlands"] = {53, 55, 56}},
        },
        [179] = {
            id=179,
            label=Locale["613_defeat_of_the_jailer"],
            chapters={{
                header = Locale[""],
                pages = {Locale["614_the_jailer_is_defeated_in_the_sepulcher__ending_hi"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=4,
            timeline=1,
            order=4,
            characters={["legion"] = {65}, ["shadowlands"] = {74, 76}},
            factions={["greatwars"] = {1, 15}, ["shadowlands"] = {53, 56}},
        },
        [298] = {
            id=298,
            label=Locale["909_a_moment_in_verse"],
            chapters={{
                header = Locale[""],
                pages = {Locale["910_a_moment_in_verse"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [299] = {
            id=299,
            label=Locale["911_shadows_rising"],
            chapters={{
                header = Locale[""],
                pages = {Locale["912_shadows_rising"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=6,
            characters={},
            factions={},
        },
        [300] = {
            id=300,
            label=Locale["913_terror_by_torchlight"],
            chapters={{
                header = Locale[""],
                pages = {Locale["914_terror_by_torchlight"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=7,
            characters={},
            factions={},
        },
        [301] = {
            id=301,
            label=Locale["915_exploring_azeroth__the_eastern_kingdoms"],
            chapters={{
                header = Locale[""],
                pages = {Locale["916_exploring_azeroth__the_eastern_kingdoms"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [302] = {
            id=302,
            label=Locale["917_exploring_azeroth__kalimdor"],
            chapters={{
                header = Locale[""],
                pages = {Locale["918_exploring_azeroth__kalimdor"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [303] = {
            id=303,
            label=Locale["919_death_rising"],
            chapters={{
                header = Locale[""],
                pages = {Locale["920_death_rising"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=4,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [304] = {
            id=304,
            label=Locale["921_adventurers_and_the_knights_of_the_ebon_blade_ente"],
            chapters={{
                header = Locale[""],
                pages = {Locale["922_adventurers_and_the_knights_of_the_ebon_blade_ente"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=11,
            characters={},
            factions={["lichking"] = {33}},
        },
        [305] = {
            id=305,
            label=Locale["923_the_maw_walkers_follow_their_only_lead—the_mawswor"],
            chapters={{
                header = Locale[""],
                pages = {Locale["924_the_maw_walkers_follow_their_only_lead—the_mawswor"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=12,
            characters={},
            factions={["shadowlands"] = {54}},
        },
        [306] = {
            id=306,
            label=Locale["925_the_maw_walkers_travel_to_maldraxxus_to_discover_t"],
            chapters={{
                header = Locale[""],
                pages = {Locale["926_the_maw_walkers_travel_to_maldraxxus_to_discover_t"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=13,
            characters={["greatwars"] = {6}},
            factions={},
        },
        [307] = {
            id=307,
            label=Locale["927_the_maw_walkers_travel_to_ardenweald_to_deliver_th"],
            chapters={{
                header = Locale[""],
                pages = {Locale["928_the_maw_walkers_travel_to_ardenweald_to_deliver_th"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=3,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [308] = {
            id=308,
            label=Locale["929_in_revendreth__the_maw_walkers_discover_that_denat"],
            chapters={{
                header = Locale[""],
                pages = {Locale["930_in_revendreth__the_maw_walkers_discover_that_denat"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=4,
            timeline=1,
            order=15,
            characters={},
            factions={},
        },
        [309] = {
            id=309,
            label=Locale["931_the_maw_walkers_join_one_of_the_four_covenants_to_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["932_the_maw_walkers_join_one_of_the_four_covenants_to_"]} }},
            yearStart=35,
            yearEnd=35,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }