local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    BurningcrusadeEventsDB = {
        [140] = {
            id=140,
            label=Locale["413_reopening_of_the_dark_portal___arrival_in_outland"],
            chapters={{
                header = Locale[""],
                pages = {Locale["414_the_dark_portal_is_reopened_from_azeroth__and_alli"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=2,
            timeline=1,
            order=0,
            characters={["burningcrusade"] = {38}},
            factions={["greatwars"] = {15, 1}, ["burningcrusade"] = {28}},
        },
        [141] = {
            id=141,
            label=Locale["415_alliance_and_horde_expedition_in_outland"],
            chapters={{
                header = Locale[""],
                pages = {Locale["416_campaigns_across_hellfire_peninsula__zangarmarsh__"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=3,
            timeline=1,
            order=1,
            characters={["burningcrusade"] = {38, 39, 41}},
            factions={["greatwars"] = {15, 1}, ["burningcrusade"] = {29, 30, 31}},
        },
        [142] = {
            id=142,
            label=Locale["417_fall_of_magtheridon_and_illidan's_rule"],
            chapters={{
                header = Locale[""],
                pages = {Locale["418_magtheridon_is_overthrown_as_illidan_consolidates_"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=4,
            timeline=1,
            order=2,
            characters={["greatwars"] = {24}, ["burningcrusade"] = {39}},
            factions={["greatwars"] = {17, 12, 1, 15}},
        },
        [143] = {
            id=143,
            label=Locale["419_tempest_keep_campaign_and_kael'thas_betrayal"],
            chapters={{
                header = Locale[""],
                pages = {Locale["420_kael'thas_turns_from_the_outland_struggle_to_serve"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=4,
            timeline=1,
            order=3,
            characters={["greatwars"] = {25}, ["burningcrusade"] = {41}},
            factions={["greatwars"] = {18}, ["burningcrusade"] = {29, 30, 31}},
        },
        [144] = {
            id=144,
            label=Locale["421_sunwell_crisis_and_defeat_of_kil'jaeden"],
            chapters={{
                header = Locale[""],
                pages = {Locale["422_at_the_sunwell__azeroth's_champions_and_blood_elf_"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=4,
            timeline=1,
            order=4,
            characters={["greatwars"] = {25}, ["burningcrusade"] = {42, 40}, ["legion"] = {68}},
            factions={["greatwars"] = {18, 12, 15, 1}},
        },
        [215] = {
            id=215,
            label=Locale["743_kil'jaeden_sends_highlord_kruul_to_build_the_burni"],
            chapters={{
                header = Locale[""],
                pages = {Locale["744_kil'jaeden_sends_highlord_kruul_to_build_the_burni"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=5,
            characters={["burningcrusade"] = {42}, ["legion"] = {68}},
            factions={},
        },
        [216] = {
            id=216,
            label=Locale["745_the_naaru_a'dal__m'uru__and_o'ros_take_the_dimensi"],
            chapters={{
                header = Locale[""],
                pages = {Locale["746_the_naaru_a'dal__m'uru__and_o'ros_take_the_dimensi"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=6,
            characters={["burningcrusade"] = {38, 41}},
            factions={},
        },
        [217] = {
            id=217,
            label=Locale["747_the_blood_elves__led_by_kael'thas_sunstrider__besi"],
            chapters={{
                header = Locale[""],
                pages = {Locale["748_the_blood_elves__led_by_kael'thas_sunstrider__besi"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=3,
            timeline=1,
            order=7,
            characters={["greatwars"] = {25}},
            factions={["greatwars"] = {18}},
        },
        [218] = {
            id=218,
            label=Locale["749_the_blood_knights_under_lady_liadrin_are_formed_by"],
            chapters={{
                header = Locale[""],
                pages = {Locale["750_the_blood_knights_under_lady_liadrin_are_formed_by"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=8,
            characters={["burningcrusade"] = {40}},
            factions={["greatwars"] = {1, 14}},
        },
        [219] = {
            id=219,
            label=Locale["751_the_ethereals_arrive_on_outland__drawn_by_kael'tha"],
            chapters={{
                header = Locale[""],
                pages = {Locale["752_the_ethereals_arrive_on_outland__drawn_by_kael'tha"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [220] = {
            id=220,
            label=Locale["753_the_destruction_of_nathreza"],
            chapters={{
                header = Locale[""],
                pages = {Locale["754_the_destruction_of_nathreza___akama_allies_himself"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [221] = {
            id=221,
            label=Locale["755_velen_leads_a_raid_to_liberate_the_exodar_and_esca"],
            chapters={{
                header = Locale[""],
                pages = {Locale["756_velen_leads_a_raid_to_liberate_the_exodar_and_esca"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=11,
            characters={["burningcrusade"] = {38}},
            factions={},
        },
        [222] = {
            id=222,
            label=Locale["757_the_blood_elves__at_the_invitation_of_sylvanas_win"],
            chapters={{
                header = Locale[""],
                pages = {Locale["758_the_blood_elves__at_the_invitation_of_sylvanas_win"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=12,
            characters={["greatwars"] = {21}, ["legion"] = {66}},
            factions={["greatwars"] = {1, 18}},
        },
        [223] = {
            id=223,
            label=Locale["759_invasion_of_outland"],
            chapters={{
                header = Locale[""],
                pages = {Locale["760_patch_2_0_3_the_burning_crusade__invasion_of_outla"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=4,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [224] = {
            id=224,
            label=Locale["761_the_burning_crusade_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["762_patch_2_0_3_the_burning_crusade__the_burning_crusa"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=3,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [225] = {
            id=225,
            label=Locale["763_the_caverns_of_time_open"],
            chapters={{
                header = Locale[""],
                pages = {Locale["764_patch_2_0_3_the_burning_crusade__nozdormu_awakens_"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=15,
            characters={},
            factions={},
        },
        [226] = {
            id=226,
            label=Locale["765_black_temple__raid"],
            chapters={{
                header = Locale[""],
                pages = {Locale["766_patch_2_1_0_the_black_temple__the_combined_allianc"]} }},
            yearStart=26,
            yearEnd=26,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }