local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    WarlordsEventsDB = {
        [160] = {
            id=160,
            label=Locale["505_dark_portal_opens_again___invasion_of_draenor"],
            chapters={{
                header = Locale[""],
                pages = {Locale["506_a_new_dark_portal_opens_onto_an_alternate_timeline"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=2,
            timeline=1,
            order=0,
            characters={["warlords"] = {60, 61}},
            factions={["greatwars"] = {15, 1}, ["warlords"] = {41, 42}},
        },
        [161] = {
            id=161,
            label=Locale["507_alliance_and_horde_struggle_for_draenor"],
            chapters={{
                header = Locale[""],
                pages = {Locale["508_both_factions_wage_war_on_alternate_draenor_agains"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=3,
            timeline=1,
            order=1,
            characters={["warlords"] = {60, 61, 62}},
            factions={["greatwars"] = {15, 1}, ["warlords"] = {41, 42, 43}},
        },
        [162] = {
            id=162,
            label=Locale["509_blackrock_foundry_and_durotan_plea"],
            chapters={{
                header = Locale[""],
                pages = {Locale["510_durotan_becomes_a_key_ally_in_the_assault_on_the_b"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=4,
            timeline=1,
            order=2,
            characters={["greatwars"] = {6, 5}, ["warlords"] = {60, 61}},
            factions={["greatwars"] = {15, 1}, ["warlords"] = {44}},
        },
        [163] = {
            id=163,
            label=Locale["511_hellfire_citadel_and_the_burning_legion_invasion"],
            chapters={{
                header = Locale[""],
                pages = {Locale["512_the_final_assault_on_hellfire_citadel_exposes_the_"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=4,
            timeline=1,
            order=3,
            characters={["burningcrusade"] = {42}, ["warlords"] = {61, 63}},
            factions={["greatwars"] = {12, 15, 1}},
        },
        [164] = {
            id=164,
            label=Locale["513_timeline_divergence_and_escape_from_draenor"],
            chapters={{
                header = Locale[""],
                pages = {Locale["514_with_alternate_draenor_crumbling__survivors_escape"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=4,
            characters={["warlords"] = {60, 61}},
            factions={["greatwars"] = {15, 1}},
        },
        [263] = {
            id=263,
            label=Locale["839_blood_and_thunder__comic___past"],
            chapters={{
                header = Locale[""],
                pages = {Locale["840_blood_and_thunder__comic___past"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [264] = {
            id=264,
            label=Locale["841_blackhand__comic"],
            chapters={{
                header = Locale[""],
                pages = {Locale["842_blackhand__comic"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=6,
            characters={["greatwars"] = {9}},
            factions={},
        },
        [265] = {
            id=265,
            label=Locale["843_blackfathom_deeps__dungeon"],
            chapters={{
                header = Locale[""],
                pages = {Locale["844_patch_6_0_2_the_iron_tide__twilight_lord_bathiel_a"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=7,
            characters={},
            factions={},
        },
        [266] = {
            id=266,
            label=Locale["845_razorfen_kraul__dungeon"],
            chapters={{
                header = Locale[""],
                pages = {Locale["846_patch_6_0_2_the_iron_tide__charlga_razorflank__mak"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [267] = {
            id=267,
            label=Locale["847_razorfen_downs__dungeon"],
            chapters={{
                header = Locale[""],
                pages = {Locale["848_patch_6_0_2_the_iron_tide__death_speaker_blackthor"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [268] = {
            id=268,
            label=Locale["849_the_dark_portal_on_alternate_draenor_is_finished_a"],
            chapters={{
                header = Locale[""],
                pages = {Locale["850_patch_6_0_2_the_iron_tide__the_dark_portal_on_alte"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [269] = {
            id=269,
            label=Locale["851_warlords_of_draenor_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["852_patch_6_0_3a_warlords_of_draenor__in_retaliation__"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=3,
            timeline=1,
            order=11,
            characters={},
            factions={},
        },
        [270] = {
            id=270,
            label=Locale["853_grommash's_failure_breeds_dissent_within_the_ranks"],
            chapters={{
                header = Locale[""],
                pages = {Locale["854_patch_6_1_0_garrisons_update__grommash's_failure_b"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=3,
            timeline=1,
            order=12,
            characters={["greatwars"] = {13}},
            factions={},
        },
        [271] = {
            id=271,
            label=Locale["855_gul'dan_takes_control_of_hellfire_citadel__intendi"],
            chapters={{
                header = Locale[""],
                pages = {Locale["856_patch_6_2_0_fury_of_hellfire__gul'dan_takes_contro"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=13,
            characters={["greatwars"] = {13}},
            factions={},
        },
        [272] = {
            id=272,
            label=Locale["857_tanaan_jungle_storyline"],
            chapters={{
                header = Locale[""],
                pages = {Locale["858_patch_6_2_0_fury_of_hellfire__the_horde_and_allian"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [273] = {
            id=273,
            label=Locale["859_heroes_return_to_azeroth__closing_the_way_to_the_a"],
            chapters={{
                header = Locale[""],
                pages = {Locale["860_patch_6_2_0_fury_of_hellfire__heroes_return_to_aze"]} }},
            yearStart=30,
            yearEnd=30,
            eventType=1,
            timeline=1,
            order=15,
            characters={},
            factions={},
        }
    }