local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    WorldofwarcraftEventsDB = {
        [131] = {
            id=131,
            label=Locale["359_world_of_warcraft_classic_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["360_in_the_wake_of_the_third_war__azeroth_enters_the_a"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=2,
            timeline=1,
            order=0,
            characters={},
            factions={["greatwars"] = {15, 1}, ["worldofwarcraft"] = {22}},
        },
        [132] = {
            id=132,
            label=Locale["361_ragefire_chasm_and_the_shadow_council_in_orgrimmar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["362_cultists_and_infiltrators_tied_to_the_shadow_counc"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=1,
            characters={},
            factions={["greatwars"] = {1, 4}},
        },
        [133] = {
            id=133,
            label=Locale["363_blackrock_depths___moira_bronzebeard_kidnapped"],
            chapters={{
                header = Locale[""],
                pages = {Locale["364_dagran_thaurissan's_hold_over_blackrock_depths_and"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=2,
            characters={["worldofwarcraft"] = {32, 33}},
            factions={["greatwars"] = {15}, ["worldofwarcraft"] = {23}},
        },
        [134] = {
            id=134,
            label=Locale["365_stratholme___baron_rivendare_and_the_scarlet_crusa"],
            chapters={{
                header = Locale[""],
                pages = {Locale["366_the_ruined_city_of_stratholme_remains_a_battlegrou"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=3,
            characters={["worldofwarcraft"] = {34}},
            factions={["greatwars"] = {13}, ["worldofwarcraft"] = {24}},
        },
        [135] = {
            id=135,
            label=Locale["367_naxxramas_and_the_scourge_invasion"],
            chapters={{
                header = Locale[""],
                pages = {Locale["368_kel'thuzad's_necropolis_naxxramas_looms_over_azero"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=4,
            timeline=1,
            order=4,
            characters={["greatwars"] = {22}},
            factions={["greatwars"] = {13}},
        },
        [136] = {
            id=136,
            label=Locale["369_blackwing_lair_and_nefarian's_defeat"],
            chapters={{
                header = Locale[""],
                pages = {Locale["370_deep_within_blackwing_lair__nefarian_advances_twis"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=4,
            timeline=1,
            order=5,
            characters={["worldofwarcraft"] = {35}},
            factions={["worldofwarcraft"] = {25}},
        },
        [137] = {
            id=137,
            label=Locale["371_zul'gurub_and_the_return_of_hakkar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["372_hakkar_the_soulflayer_manifests_again_in_zul'gurub"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=4,
            timeline=1,
            order=6,
            characters={["worldofwarcraft"] = {36}},
            factions={["worldofwarcraft"] = {26, 22}},
        },
        [138] = {
            id=138,
            label=Locale["373_war_of_ahn'qiraj___awakening_of_c'thun"],
            chapters={{
                header = Locale[""],
                pages = {Locale["374_the_gates_of_ahn'qiraj_are_opened_and_the_armies_o"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=7,
            characters={["worldofwarcraft"] = {37}},
            factions={["greatwars"] = {15, 1}, ["worldofwarcraft"] = {22, 27}},
        },
        [139] = {
            id=139,
            label=Locale["375_end_of_classic___rising_alliance_horde_tensions"],
            chapters={{
                header = Locale[""],
                pages = {Locale["376_as_classic_draws_to_a_close__the_greatest_threats_"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=8,
            characters={["greatwars"] = {7, 20}},
            factions={["greatwars"] = {15, 1}},
        },
        [203] = {
            id=203,
            label=Locale["719_gnomeregan_is_lost_after_sicco_thermaplugg_convinc"],
            chapters={{
                header = Locale[""],
                pages = {Locale["720_gnomeregan_is_lost_after_sicco_thermaplugg_convinc"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [204] = {
            id=204,
            label=Locale["721_king_varian_wrynn_is_kidnapped__bolvar_fordragon_b"],
            chapters={{
                header = Locale[""],
                pages = {Locale["722_king_varian_wrynn_is_kidnapped__bolvar_fordragon_b"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=10,
            characters={["lichking"] = {43}, ["cataclysm"] = {48}, ["legion"] = {64}, ["shadowlands"] = {76}},
            factions={["greatwars"] = {2}},
        },
        [205] = {
            id=205,
            label=Locale["723_the_lich_king_reawakens_after_arthas'_will_overpow"],
            chapters={{
                header = Locale[""],
                pages = {Locale["724_the_lich_king_reawakens_after_arthas'_will_overpow"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=4,
            timeline=1,
            order=11,
            characters={["greatwars"] = {31}},
            factions={},
        },
        [206] = {
            id=206,
            label=Locale["725_world_of_warcraft_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["726_patch_1_1_0_world_of_warcraft__world_of_warcraft_c"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=12,
            characters={},
            factions={},
        },
        [207] = {
            id=207,
            label=Locale["727_dagran_thaurissan__emperor_of_the_dark_iron_clan__"],
            chapters={{
                header = Locale[""],
                pages = {Locale["728_patch_1_1_0_world_of_warcraft__dagran_thaurissan__"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=13,
            characters={["worldofwarcraft"] = {32}},
            factions={},
        },
        [208] = {
            id=208,
            label=Locale["729_molten_core__raid"],
            chapters={{
                header = Locale[""],
                pages = {Locale["730_patch_1_1_0_world_of_warcraft__moira_thaurissan_sp"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [209] = {
            id=209,
            label=Locale["731_the_horde_investigates_the_increased_aggression_of"],
            chapters={{
                header = Locale[""],
                pages = {Locale["732_patch_1_2_0_mysteries_of_maraudon__the_horde_inves"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=15,
            characters={},
            factions={["greatwars"] = {1}},
        },
        [210] = {
            id=210,
            label=Locale["733_king_gordok_of_the_gordunni_sends_his_people_out_t"],
            chapters={{
                header = Locale[""],
                pages = {Locale["734_patch_1_3_0_ruins_of_the_dire_maul__king_gordok_of"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        },
        [211] = {
            id=211,
            label=Locale["735_short_john_mithril_begins_hosting_nonlethal_free_f"],
            chapters={{
                header = Locale[""],
                pages = {Locale["736_patch_1_4_0_the_call_to_war__short_john_mithril_be"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=17,
            characters={},
            factions={},
        },
        [212] = {
            id=212,
            label=Locale["737_elemental_invasions"],
            chapters={{
                header = Locale[""],
                pages = {Locale["738_patch_1_4_0_the_call_to_war__elemental_invasions__"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=18,
            characters={},
            factions={},
        },
        [213] = {
            id=213,
            label=Locale["739_warsong_gulch_and_alterac_valley__battlegrounds"],
            chapters={{
                header = Locale[""],
                pages = {Locale["740_patch_1_5_0_battlegrounds__skirmishes_between_the_"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=3,
            timeline=1,
            order=19,
            characters={},
            factions={},
        },
        [214] = {
            id=214,
            label=Locale["741_the_darkmoon_faire_gains_traction_and_comes_to_mul"],
            chapters={{
                header = Locale[""],
                pages = {Locale["742_patch_1_6_0_assault_on_blackwing_lair__the_darkmoo"]} }},
            yearStart=25,
            yearEnd=25,
            eventType=1,
            timeline=1,
            order=20,
            characters={},
            factions={},
        }
    }