--[[
    HTMLContentTemplate.lua
    
    Single HTML container mixin for the new Chronicles book system.
    Displays complete HTML documents generated by HTMLBuilder.
    
    This replaces the multi-template system with a single, unified container
    that can display any type of content through HTML.
]]
local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

-- =============================================================================================
-- HTML CONTENT MIXIN
-- =============================================================================================

--[[
    Mixin for the new unified HTML content display
    Handles single HTML documents with all content types integrated
]]
HTMLContentMixin = {}

--[[
    Initialize HTML content display with complete HTML document
    @param elementData [table] Element data with complete HTML content
]]
function HTMLContentMixin:Init(elementData)
    if not elementData then
        self:ShowError(Locale["BOOK_ERROR_NO_CONTENT_DATA"])
        return
    end

    -- Use htmlContent exclusively
    local htmlContent = elementData.htmlContent

    if not htmlContent or htmlContent == "" then
        self:ShowError(Locale["BOOK_ERROR_NO_HTML"])
        return
    end

    -- Set the HTML content in the scroll frame
    if self.ScrollFrame and self.ScrollFrame.HTML then
        local htmlContainer = self.ScrollFrame.HTML
        htmlContainer:SetText(htmlContent)

        -- Enable hyperlinks
        htmlContainer:SetHyperlinksEnabled(true)

        -- Set up hyperlink click handler
        htmlContainer:SetScript(
            "OnHyperlinkClick",
            function(frame, link, text, button)
                self:OnHyperlinkClick(link, text, button)
            end
        )

        -- Scroll to top
        self.ScrollFrame:SetVerticalScroll(0)

        -- Show the content
        htmlContainer:Show()
        self:Show()
    else
        self:ShowError(Locale["BOOK_ERROR_NO_DISPLAY"])
    end
end

--[[
    Show an error message when content cannot be displayed
    @param errorMessage [string] Error description
]]
function HTMLContentMixin:ShowError(errorMessage)
    errorMessage = errorMessage or Locale["BOOK_ERROR_UNKNOWN"]

    -- Create simple HTML error message compatible with SimpleHTML
    local errorHTML =
        string.format([[<html><body><h1>%s</h1><p>%s</p></body></html>]], Locale["BOOK_ERROR_TITLE"], errorMessage)

    if self.ScrollFrame and self.ScrollFrame.HTML then
        -- SetText can reject malformed markup. Failing here means the error notice itself cannot be
        -- drawn, which would otherwise leave a blank frame and no clue -- so report rather than
        -- swallow. geterrorhandler does not route back through this mixin, so there is no cascade.
        local ok, err =
            pcall(
            function()
                self.ScrollFrame.HTML:SetText(errorHTML)
            end
        )
        if not ok then
            geterrorhandler()(err)
        end

        self:SetHeight(150)
        self:Show()
    end

    self.isLoaded = false
end

--[[
    Handle hyperlink clicks for Chronicles navigation
    @param link [string] The link href value
    @param text [string] The link text
    @param button [string] The mouse button used
]]
function HTMLContentMixin:OnHyperlinkClick(link, text, button)
    -- Parse Chronicles links.
    --
    -- Only "chapter" is handled, because only chapter links are ever generated — the table of
    -- contents builds them in HTMLBuilder.CreateTableOfContents. Cross-entity links
    -- (chronicles:event:<id> and friends) are not produced anywhere, and the handlers that once
    -- existed for them were wrong: they wrote a bare id into the selection state where every
    -- consumer expects a {<kind>Id, collectionName} table. Re-adding entity navigation means
    -- teaching HTMLBuilder.CreateLink to emit collection-qualified link data first, since an id
    -- alone cannot identify a record across collections.
    if not link:match("^chronicles:") then
        return
    end

    local linkType, linkData = link:match("^chronicles:([^:]+):(.+)$")
    if linkType == "chapter" then
        self:NavigateToChapter(linkData)
    end
end

--[[
    Convert a document index into the page the pager displays it on.

    Two different units meet here. navigationData.pageMapping counts *documents*, because HTMLBuilder
    has no access to the book frame. The pager counts *spreads*: viewsPerPage documents share one
    displayed page, so document 5 is on page 3 at the book's viewsPerPage of 2. Handing a document
    index straight to SetCurrentPage is only invisible while a book is short enough that the two
    numbers coincide, which is every book in the reduced content set and no book with real chapters.

    PagedContentFrameBaseMixin ships GetPageForViewDataIndex, which is exactly this arithmetic against
    the frame's own viewsPerPage; the fallback covers a frame that has not wired it up yet and still
    reads viewsPerPage from the frame rather than assuming 2.

    @param pagedDetails [table] The book's PagedDetails frame
    @param documentIndex [number] 1-based index into the htmlDocuments array
    @return [number] 1-based displayed page number
]]
local function DocumentIndexToPage(pagedDetails, documentIndex)
    if pagedDetails and pagedDetails.GetPageForViewDataIndex then
        return pagedDetails:GetPageForViewDataIndex(documentIndex)
    end

    local viewsPerPage = (pagedDetails and pagedDetails.viewsPerPage) or 1
    if viewsPerPage < 1 then
        viewsPerPage = 1
    end

    return math.ceil(documentIndex / viewsPerPage)
end

HTMLContentMixin.DocumentIndexToPage = DocumentIndexToPage

--[[
    Navigate to a specific chapter
    @param chapterData [string] Chapter identifier
]]
function HTMLContentMixin:NavigateToChapter(chapterData)
    -- Find the parent BookContainer
    local bookContainer = self:GetParent()
    while bookContainer and not bookContainer.PagedDetails do
        bookContainer = bookContainer:GetParent()
    end

    if not bookContainer or not bookContainer.navigationData then
        return
    end

    -- navigationData.pageMapping holds chapter id -> document index
    local documentIndex = bookContainer.navigationData.pageMapping[chapterData]
    if not documentIndex then
        return
    end

    local pagedDetails = bookContainer.PagedDetails
    local pageIndex = DocumentIndexToPage(pagedDetails, documentIndex)

    if pagedDetails and pagedDetails.SetCurrentPage then
        pagedDetails:SetCurrentPage(pageIndex)
    elseif pagedDetails and pagedDetails.PagingControls and pagedDetails.PagingControls.SetCurrentPage then
        pagedDetails.PagingControls:SetCurrentPage(pageIndex)
    end
end
