local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    BattleforazerothEventsDB = {
        [170] = {
            id=170,
            label=Locale["559_burning_of_teldrassil"],
            chapters={{
                header = Locale[""],
                pages = {Locale["560_sylvanas_orders_the_burning_of_teldrassil__escalat"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=4,
            timeline=1,
            order=0,
            characters={["legion"] = {66, 65}},
            factions={["greatwars"] = {1, 15}},
        },
        [171] = {
            id=171,
            label=Locale["561_siege_of_lordaeron"],
            chapters={{
                header = Locale[""],
                pages = {Locale["562_alliance_forces_besiege_lordaeron_in_retaliation__"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=1,
            characters={["legion"] = {66, 65}},
            factions={["greatwars"] = {1, 15}, ["battleforazeroth"] = {52}},
        },
        [172] = {
            id=172,
            label=Locale["563_battle_of_dazar'alor___zandalari_join_the_horde"],
            chapters={{
                header = Locale[""],
                pages = {Locale["564_the_battle_at_dazar'alor_ends_with_the_death_of_ra"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=2,
            characters={["legion"] = {65}, ["battleforazeroth"] = {70, 71}},
            factions={["greatwars"] = {1}, ["battleforazeroth"] = {48, 49}},
        },
        [173] = {
            id=173,
            label=Locale["565_nazjatar_campaign___rise_of_n'zoth"],
            chapters={{
                header = Locale[""],
                pages = {Locale["566_azshara_lures_both_factions_into_nazjatar_and_the_"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=3,
            characters={["battleforazeroth"] = {72, 73}},
            factions={["battleforazeroth"] = {51, 50, 52}},
        },
        [174] = {
            id=174,
            label=Locale["567_ny'alotha___defeat_of_n'zoth"],
            chapters={{
                header = Locale[""],
                pages = {Locale["568_azeroth's_champions_invade_ny'alotha_and_end_n'zot"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=4,
            timeline=1,
            order=4,
            characters={["legion"] = {66, 65}, ["battleforazeroth"] = {73}},
            factions={["greatwars"] = {1, 15}, ["battleforazeroth"] = {50, 52}},
        },
        [286] = {
            id=286,
            label=Locale["885_jaina__reunion__comic"],
            chapters={{
                header = Locale[""],
                pages = {Locale["886_jaina__reunion__comic"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [287] = {
            id=287,
            label=Locale["887_magni__the_speaker__comic"],
            chapters={{
                header = Locale[""],
                pages = {Locale["888_magni__the_speaker__comic"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=6,
            characters={},
            factions={},
        },
        [288] = {
            id=288,
            label=Locale["889_windrunner__three_sisters__comic"],
            chapters={{
                header = Locale[""],
                pages = {Locale["890_windrunner__three_sisters__comic"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=7,
            characters={},
            factions={},
        },
        [289] = {
            id=289,
            label=Locale["891_warbringers_jaina__animated_short"],
            chapters={{
                header = Locale[""],
                pages = {Locale["892_warbringers_jaina__animated_short"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [290] = {
            id=290,
            label=Locale["893_warbringers_sylvanas__animated_short___present"],
            chapters={{
                header = Locale[""],
                pages = {Locale["894_warbringers_sylvanas__animated_short___present"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [291] = {
            id=291,
            label=Locale["895_before_the_storm"],
            chapters={{
                header = Locale[""],
                pages = {Locale["896_before_the_storm"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [292] = {
            id=292,
            label=Locale["897_the_fourth_war_begins_with_the_burning_of_teldrass"],
            chapters={{
                header = Locale[""],
                pages = {Locale["898_patch_8_0_1_battle_for_azeroth__the_fourth_war_beg"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=11,
            characters={},
            factions={},
        },
        [293] = {
            id=293,
            label=Locale["899_battle_for_lordaeron"],
            chapters={{
                header = Locale[""],
                pages = {Locale["900_patch_8_0_1_battle_for_azeroth__battle_for_lordaer"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=12,
            characters={},
            factions={},
        },
        [294] = {
            id=294,
            label=Locale["901_war_in_kul_tiras___war_in_zandalar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["902_patch_8_0_1_battle_for_azeroth__war_in_kul_tiras__"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [295] = {
            id=295,
            label=Locale["903_battle_for_stromgarde"],
            chapters={{
                header = Locale[""],
                pages = {Locale["904_patch_8_0_1_battle_for_azeroth__battle_for_stromga"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=3,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [296] = {
            id=296,
            label=Locale["905_the_alliance_and_the_horde_respectively_ally_with_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["906_patch_8_0_1_battle_for_azeroth__the_alliance_and_t"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=15,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [297] = {
            id=297,
            label=Locale["907_uldir"],
            chapters={{
                header = Locale[""],
                pages = {Locale["908_patch_8_0_1_battle_for_azeroth__uldir"]} }},
            yearStart=32,
            yearEnd=32,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }