local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    LegionEventsDB = {
        [165] = {
            id=165,
            label=Locale["549_broken_shore_invasion___deaths_of_varian_and_vol'j"],
            chapters={{
                header = Locale[""],
                pages = {Locale["550_the_burning_legion_overwhelms_azeroth's_united_arm"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=2,
            timeline=1,
            order=0,
            characters={["legion"] = {64, 66}},
            factions={["greatwars"] = {15, 1, 12}},
        },
        [166] = {
            id=166,
            label=Locale["551_sylvanas_named_warchief___anduin_crowned"],
            chapters={{
                header = Locale[""],
                pages = {Locale["552_in_the_aftermath_of_the_broken_shore__sylvanas_bec"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=1,
            characters={["legion"] = {65, 66}},
            factions={["greatwars"] = {1, 15}},
        },
        [167] = {
            id=167,
            label=Locale["553_illidari_return_and_legionfall_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["554_the_illidari_and_allied_champions_launch_the_legio"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=2,
            characters={["legion"] = {67, 65}},
            factions={["greatwars"] = {12, 17}, ["legion"] = {45, 46}},
        },
        [168] = {
            id=168,
            label=Locale["555_argus_campaign___fall_of_kil'jaeden"],
            chapters={{
                header = Locale[""],
                pages = {Locale["556_the_war_expands_to_argus_where_the_army_of_the_lig"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=4,
            timeline=1,
            order=3,
            characters={["burningcrusade"] = {42}, ["legion"] = {67, 68}},
            factions={["greatwars"] = {12}, ["legion"] = {47, 46}},
        },
        [169] = {
            id=169,
            label=Locale["557_sargeras_imprisoned___azeroth_wounded"],
            chapters={{
                header = Locale[""],
                pages = {Locale["558_the_pantheon_imprisons_sargeras__but_his_final_str"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=4,
            timeline=1,
            order=4,
            characters={["legion"] = {69, 67, 65}},
            factions={["greatwars"] = {15, 1}, ["legion"] = {47}},
        },
        [274] = {
            id=274,
            label=Locale["861_king_magni_bronzebeard_awakens_in_old_ironforge"],
            chapters={{
                header = Locale[""],
                pages = {Locale["862_king_magni_bronzebeard_awakens_in_old_ironforge"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=5,
            characters={["future"] = {87}},
            factions={},
        },
        [275] = {
            id=275,
            label=Locale["863_gul'dan_re_opens_the_sealed_portal_inside_the_tomb"],
            chapters={{
                header = Locale[""],
                pages = {Locale["864_gul'dan_re_opens_the_sealed_portal_inside_the_tomb"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=6,
            characters={["greatwars"] = {13}, ["legion"] = {69}},
            factions={},
        },
        [276] = {
            id=276,
            label=Locale["865_khadgar_warns_the_faction_leaders_of_the_legion's_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["866_khadgar_warns_the_faction_leaders_of_the_legion's_"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=7,
            characters={["greatwars"] = {2}},
            factions={},
        },
        [277] = {
            id=277,
            label=Locale["867_battle_for_the_broken_shore__legion_intro_experien"],
            chapters={{
                header = Locale[""],
                pages = {Locale["868_patch_7_0_3_legion__the_alliance_and_horde_attack_"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [278] = {
            id=278,
            label=Locale["869_gul'dan_and_his_legion_penetrate_the_vault_of_the_"],
            chapters={{
                header = Locale[""],
                pages = {Locale["870_patch_7_0_3_legion__gul'dan_and_his_legion_penetra"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=9,
            characters={["greatwars"] = {13}},
            factions={},
        },
        [279] = {
            id=279,
            label=Locale["871_legion_invasions___the_legion_openly_launches_full"],
            chapters={{
                header = Locale[""],
                pages = {Locale["872_patch_7_0_3_legion__legion_invasions___the_legion_"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [280] = {
            id=280,
            label=Locale["873_dalaran_is_moved_above_karazhan_while_khadgar__mag"],
            chapters={{
                header = Locale[""],
                pages = {Locale["874_patch_7_0_3_legion__dalaran_is_moved_above_karazha"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=11,
            characters={["greatwars"] = {2}, ["lichking"] = {46}},
            factions={},
        },
        [281] = {
            id=281,
            label=Locale["875_legion_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["876_patch_7_0_3_legion__dalaran_is_moved_to_the_broken"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=12,
            characters={},
            factions={},
        },
        [282] = {
            id=282,
            label=Locale["877_the_nighthold__raid____alternate_gul'dan_is_defeat"],
            chapters={{
                header = Locale[""],
                pages = {Locale["878_patch_7_1_5__the_nighthold__raid____alternate_gul'"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=4,
            timeline=1,
            order=13,
            characters={["greatwars"] = {13}},
            factions={},
        },
        [283] = {
            id=283,
            label=Locale["879_assault_on_broken_shore__broken_shore_storyline"],
            chapters={{
                header = Locale[""],
                pages = {Locale["880_patch_7_2_0_the_tomb_of_sargeras__the_armies_of_le"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=3,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [284] = {
            id=284,
            label=Locale["881_anduin__son_of_the_wolf__comic___present__»__appox"],
            chapters={{
                header = Locale[""],
                pages = {Locale["882_patch_7_2_0_the_tomb_of_sargeras__anduin__son_of_t"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=15,
            characters={},
            factions={},
        },
        [285] = {
            id=285,
            label=Locale["883_wailing_critters__scenario"],
            chapters={{
                header = Locale[""],
                pages = {Locale["884_patch_7_2_0_the_tomb_of_sargeras__a_shadowy_figure"]} }},
            yearStart=31,
            yearEnd=31,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }