local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    MistsofpandariaEventsDB = {
        [155] = {
            id=155,
            label=Locale["495_discovery_of_pandaria"],
            chapters={{
                header = Locale[""],
                pages = {Locale["496_the_land_of_pandaria_emerges_from_the_mists__and_b"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=2,
            timeline=1,
            order=0,
            characters={["mistsofpandaria"] = {53, 54}},
            factions={["greatwars"] = {15, 1}},
        },
        [156] = {
            id=156,
            label=Locale["497_jade_forest_and_mantid_awakening"],
            chapters={{
                header = Locale[""],
                pages = {Locale["498_the_jade_forest_becomes_a_battleground_as_the_mant"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=3,
            timeline=1,
            order=1,
            characters={["mistsofpandaria"] = {55, 56}},
            factions={["greatwars"] = {15, 1}, ["mistsofpandaria"] = {39, 40}},
        },
        [157] = {
            id=157,
            label=Locale["499_domination_point_and_aggression_in_vale"],
            chapters={{
                header = Locale[""],
                pages = {Locale["500_the_vale_of_eternal_blossoms_transforms_into_a_war"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=2,
            characters={["mistsofpandaria"] = {53, 54}},
            factions={["greatwars"] = {15, 1}, ["mistsofpandaria"] = {39, 40}},
        },
        [158] = {
            id=158,
            label=Locale["501_heart_of_fear_and_terrace_of_endless_spring"],
            chapters={{
                header = Locale[""],
                pages = {Locale["502_alliance_and_horde_adventurers_raid_the_heart_of_f"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=4,
            timeline=1,
            order=3,
            characters={["mistsofpandaria"] = {57, 58}},
            factions={["greatwars"] = {15, 1}, ["mistsofpandaria"] = {39, 40}},
        },
        [159] = {
            id=159,
            label=Locale["503_siege_of_orgrimmar___garrosh_fall"],
            chapters={{
                header = Locale[""],
                pages = {Locale["504_the_siege_of_orgrimmar_ends_garrosh_tyranny_and_re"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=4,
            timeline=1,
            order=4,
            characters={["cataclysm"] = {49}, ["mistsofpandaria"] = {54, 59}},
            factions={["greatwars"] = {1, 15}, ["mistsofpandaria"] = {39}},
        },
        [251] = {
            id=251,
            label=Locale["815_ragefire_chasm__dungeon____dark_shaman_take_up_res"],
            chapters={{
                header = Locale[""],
                pages = {Locale["816_patch_5_0_4_mists_of_pandaria__ragefire_chasm__dun"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [252] = {
            id=252,
            label=Locale["817_scarlet_monastery"],
            chapters={{
                header = Locale[""],
                pages = {Locale["818_patch_5_0_4_mists_of_pandaria__scarlet_monastery__"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=6,
            characters={},
            factions={},
        },
        [253] = {
            id=253,
            label=Locale["819_scholomance__dungeon"],
            chapters={{
                header = Locale[""],
                pages = {Locale["820_patch_5_0_4_mists_of_pandaria__scholomance__dungeo"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=7,
            characters={},
            factions={},
        },
        [254] = {
            id=254,
            label=Locale["821_silvershard_mines__battleground"],
            chapters={{
                header = Locale[""],
                pages = {Locale["822_patch_5_0_4_mists_of_pandaria__the_horde_and_allia"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=3,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [255] = {
            id=255,
            label=Locale["823_as_the_horde_prepares_to_invade_theramore__escalat"],
            chapters={{
                header = Locale[""],
                pages = {Locale["824_patch_5_0_4_mists_of_pandaria__as_the_horde_prepar"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=9,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [256] = {
            id=256,
            label=Locale["825_attack_on_theramore_isle"],
            chapters={{
                header = Locale[""],
                pages = {Locale["826_patch_5_0_4_mists_of_pandaria__attack_on_theramore"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [257] = {
            id=257,
            label=Locale["827_wandering_isle_storyline"],
            chapters={{
                header = Locale[""],
                pages = {Locale["828_patch_5_0_4_mists_of_pandaria__wandering_isle_stor"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=11,
            characters={},
            factions={},
        },
        [258] = {
            id=258,
            label=Locale["829_pandaria_is_accidentally_discovered_by_the_allianc"],
            chapters={{
                header = Locale[""],
                pages = {Locale["830_patch_5_0_4_mists_of_pandaria__pandaria_is_acciden"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=12,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [259] = {
            id=259,
            label=Locale["831_mists_of_pandaria_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["832_patch_5_0_4_mists_of_pandaria__the_alliance_and_ho"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=3,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [260] = {
            id=260,
            label=Locale["833_operation__shieldwall_and_dominance_offensive"],
            chapters={{
                header = Locale[""],
                pages = {Locale["834_patch_5_1_0_landfall__operation__shieldwall_and_do"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=4,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [261] = {
            id=261,
            label=Locale["835_assault_on_zan'vess__scenario"],
            chapters={{
                header = Locale[""],
                pages = {Locale["836_patch_5_1_0_landfall__champions_assault_grand_empr"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=3,
            timeline=1,
            order=15,
            characters={},
            factions={},
        },
        [262] = {
            id=262,
            label=Locale["837_garrosh's_agents_raid_darnassus_to_steal_the"],
            chapters={{
                header = Locale[""],
                pages = {Locale["838_patch_5_1_0_landfall__garrosh's_agents_raid_darnas"]} }},
            yearStart=29,
            yearEnd=29,
            eventType=1,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }