local FOLDER_NAME, private = ...
local Locale = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)

    CataclysmEventsDB = {
        [150] = {
            id=150,
            label=Locale["467_the_shattering___return_of_deathwing"],
            chapters={{
                header = Locale[""],
                pages = {Locale["468_deathwing_erupts_from_deepholm__shattering_azeroth"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=2,
            timeline=1,
            order=0,
            characters={["greatwars"] = {15, 7}, ["cataclysm"] = {52}},
            factions={["greatwars"] = {15, 1}, ["cataclysm"] = {37}},
        },
        [151] = {
            id=151,
            label=Locale["469_worgen_and_goblins_enter_the_faction_war"],
            chapters={{
                header = Locale[""],
                pages = {Locale["470_gilnean_worgen_join_the_alliance_while_bilgewater_"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=1,
            characters={["cataclysm"] = {48, 49}},
            factions={["greatwars"] = {15, 1}},
        },
        [152] = {
            id=152,
            label=Locale["471_twilight's_hammer_uprising"],
            chapters={{
                header = Locale[""],
                pages = {Locale["472_cho'gall's_cult_spreads_chaos_across_azeroth_as_th"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=3,
            timeline=1,
            order=2,
            characters={["greatwars"] = {7}, ["cataclysm"] = {50}},
            factions={["greatwars"] = {15, 1}, ["cataclysm"] = {35, 36}},
        },
        [153] = {
            id=153,
            label=Locale["473_firelands_campaign___fall_of_ragnaros"],
            chapters={{
                header = Locale[""],
                pages = {Locale["474_the_campaign_into_the_firelands_ends_with_ragnaros"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=4,
            timeline=1,
            order=3,
            characters={["cataclysm"] = {51}},
            factions={["greatwars"] = {15, 1}, ["cataclysm"] = {38, 36}},
        },
        [154] = {
            id=154,
            label=Locale["475_dragon_soul___deathwing's_defeat"],
            chapters={{
                header = Locale[""],
                pages = {Locale["476_thrall_and_the_united_dragonflights_wield_the_drag"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=4,
            timeline=1,
            order=4,
            characters={["greatwars"] = {15, 7}, ["cataclysm"] = {52}},
            factions={["greatwars"] = {15, 1}, ["cataclysm"] = {37}},
        },
        [239] = {
            id=239,
            label=Locale["791_elemental_unrest"],
            chapters={{
                header = Locale[""],
                pages = {Locale["792_deathwing_aborbs_great_elemental_powers_within_dee"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=5,
            characters={},
            factions={},
        },
        [240] = {
            id=240,
            label=Locale["793_alliance_horde_war_begins"],
            chapters={{
                header = Locale[""],
                pages = {Locale["794_garrosh_begins_invading_alliance_territory__and_ca"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=3,
            timeline=1,
            order=6,
            characters={},
            factions={["greatwars"] = {1, 15}},
        },
        [241] = {
            id=241,
            label=Locale["795_the_cataclysm___deathwing_returns_to_azeroth__scar"],
            chapters={{
                header = Locale[""],
                pages = {Locale["796_patch_4_0_3a_the_shattering__the_cataclysm___death"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=4,
            timeline=1,
            order=7,
            characters={["greatwars"] = {15}},
            factions={},
        },
        [242] = {
            id=242,
            label=Locale["797_various_leaders_of_azeroth_face_inner_turmoil_in_t"],
            chapters={{
                header = Locale[""],
                pages = {Locale["798_patch_4_0_3a_the_shattering__various_leaders_of_az"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=8,
            characters={},
            factions={},
        },
        [243] = {
            id=243,
            label=Locale["799_cataclysm_campaign"],
            chapters={{
                header = Locale[""],
                pages = {Locale["800_patch_4_0_3a_the_shattering__deathwing's_wake_of_d"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=3,
            timeline=1,
            order=9,
            characters={},
            factions={},
        },
        [244] = {
            id=244,
            label=Locale["801_traveler__novel___approx"],
            chapters={{
                header = Locale[""],
                pages = {Locale["802_patch_4_0_3a_the_shattering__traveler__novel___app"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=10,
            characters={},
            factions={},
        },
        [245] = {
            id=245,
            label=Locale["803_the_gurubashi_and_amani_trolls_unite_under_the_zan"],
            chapters={{
                header = Locale[""],
                pages = {Locale["804_patch_4_1_0_rise_of_the_zandalari__the_gurubashi_a"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=11,
            characters={},
            factions={["greatwars"] = {10}},
        },
        [246] = {
            id=246,
            label=Locale["805_while_alexstrasza__ysera__and_the_remaining_leader"],
            chapters={{
                header = Locale[""],
                pages = {Locale["806_patch_4_1_0_rise_of_the_zandalari__while_alexstras"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=4,
            timeline=1,
            order=12,
            characters={["greatwars"] = {14}, ["dragonflight"] = {79}},
            factions={},
        },
        [247] = {
            id=247,
            label=Locale["807_elemental_bonds"],
            chapters={{
                header = Locale[""],
                pages = {Locale["808_patch_4_2_0_rage_of_the_firelands__thrall_is_assau"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=13,
            characters={},
            factions={},
        },
        [248] = {
            id=248,
            label=Locale["809_firelands_invasion"],
            chapters={{
                header = Locale[""],
                pages = {Locale["810_patch_4_2_0_rage_of_the_firelands__ragnaros_and_hi"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=14,
            characters={},
            factions={},
        },
        [249] = {
            id=249,
            label=Locale["811_wrathion__with_the_help_of_a_rogue_champion__kills"],
            chapters={{
                header = Locale[""],
                pages = {Locale["812_patch_4_2_0_rage_of_the_firelands__wrathion__with_"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=1,
            timeline=1,
            order=15,
            characters={["mistsofpandaria"] = {58}},
            factions={},
        },
        [250] = {
            id=250,
            label=Locale["813_occu'thar__a_prisoner_in_baradin_hold_breaks_out_a"],
            chapters={{
                header = Locale[""],
                pages = {Locale["814_patch_4_2_0_rage_of_the_firelands__occu'thar__a_pr"]} }},
            yearStart=28,
            yearEnd=28,
            eventType=4,
            timeline=1,
            order=16,
            characters={},
            factions={},
        }
    }